trigger:
  - prod

jobs:
  - template: .azure_pipelines/build_container.yml
    parameters:
      image_base: amd64

  - template: .azure_pipelines/build_container.yml
    parameters:
      image_base: arm32v7

  - job: create_manifest
    displayName: Create and push container manifest
    dependsOn:
      - build_amd64
      - build_arm32v7
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
        displayName: 'docker login'
        env:
          DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)
          DOCKERHUB_PASSWORD: $(DOCKERHUB_PASSWORD)

      - script: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create jihartik/rfm69-mqtt-decoder:latest jihartik/rfm69-mqtt-decoder:arm32v7 jihartik/rfm69-mqtt-decoder:amd64
        displayName: 'create manifest'

      - script: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push jihartik/rfm69-mqtt-decoder:latest
        displayName: 'push manifest'
